### ISSUE TITLE
Unclear tooltip for Add Task config

### ISSUE THREAD

**Issue by KaspervanM** [KaspervanM/WASP#61]
### Description

The tooltip used now is not very informative. It is unclear what values can be expected.

### Solution

Don't use the interface as a tooltip but show which values it can contain. For example instead of `number`, use `0 | 1 | 2 | 3 | ...` and instead of `boolean` use `true | false`. Also, instead of `?`, type `(optional)` behind the options.

**Comment by evanpacini** [comment]
I made the tooltip somewhat clearer, but was unable to remove the max-width of the tooltip. I don't know why it won't cooperate. I can't collaborate any further.
